In [6]:
#pip install tensorflow

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import KFold

In [2]:
#https://www.flashscore.fr/football/monde/coupe-du-monde/resultats/

# 1. Importation de la data

In [3]:
versus=pd.read_csv("matchfiltreavecpourcentageranking2.csv",sep=';')

In [4]:
versus

date         home_team  home_score  away_score               away_team  \
0      1930             Spain           1           0          Czechoslovakia   
1      1930          Portugal           1           0          Czechoslovakia   
2      1930            Greece           2           1              Yugoslavia   
3      1930  Northern Ireland           7           0                   Wales   
4      1930             Italy           4           2             Switzerland   
...     ...               ...         ...         ...                     ...   
29648  2021           Tunisia           1           0                   Egypt   
29649  2021        Autre pays           1           2                 Algeria   
29650  2021        Autre pays           0           0                   Egypt   
29651  2021           Tunisia           0           2                 Algeria   
29652  2021     United States           1           0  Bosnia and Herzegovina   

       tournament  winner  phase_final  home_team_pourcentage_victoire  \
0               0       2            0                           85.71   
1               0       2            0                           28.57   
2               0       2            0                           50.00   
3               0       2            0                           16.67   
4               0       2            0                           55.56   
...           ...     ...          ...                             ...   
29648           0       2            0                           68.42   
29649           0       0            0                           20.00   
29650           0       1            0                           20.00   
29651           0       0            0                           68.42   
29652           0       2            0                           76.92   

       home_team_but_mis  home_team_but_enc  away_team_pourcentage_victoire  \
0                    3.1                1.1                           37.50   
1                    0.7                2.3                           37.50   
2                    2.5                2.8                           41.67   
3                    2.3                3.3                            0.00   
4                    2.8                1.6                            7.69   
...                  ...                ...                             ...   
29648                1.7                0.7                           60.00   
29649                0.8                1.8                           70.00   
29650                0.8                1.8                           60.00   
29651                1.7                0.7                           70.00   
29652                2.3                0.5                            9.52   

       away_team_but_mis  away_team_but_enc  Rang_home_team  Rang_away_team  \
0                    2.2                1.7             NaN             NaN   
1                    2.2                1.7             NaN             NaN   
2                    2.4                2.1             NaN             NaN   
3                    0.8                4.0             NaN             NaN   
4                    1.7                3.7             NaN             NaN   
...                  ...                ...             ...             ...   
29648                1.8                0.5            26.0            46.0   
29649                3.0                0.8            99.0            33.0   
29650                1.8                0.5            99.0            46.0   
29651                3.0                0.8            26.0            33.0   
29652                0.7                1.4            20.0            55.0   

       Host  
0         1  
1         1  
2         1  
3         1  
4         1  
...     ...  
29648     1  
29649     1  
29650     1  
29651     1  
29652     1  

[29653 rows x 17 columns]

In [11]:
versus=versus[versus['tournament']==1]

In [12]:
#versus=versus.reindex(range(0,len(versus)))

In [13]:
versus

date  home_team  home_score  away_score      away_team  tournament  \
43     1930    Belgium           0           3  United States           1   
44     1930     France           4           1         Mexico           1   
45     1930     Brazil           1           2     Yugoslavia           1   
46     1930       Peru           1           3        Romania           1   
47     1930  Argentina           1           0         France           1   
...     ...        ...         ...         ...            ...         ...   
27719  2018     Russia           3           4        Croatia           1   
27720  2018     France           1           0        Belgium           1   
27721  2018    Croatia           2           1        England           1   
27722  2018    Belgium           2           0        England           1   
27723  2018     France           4           2        Croatia           1   

       winner  phase_final  home_team_pourcentage_victoire  home_team_but_mis  \
43          0            0                           38.46                2.2   
44          2            0                           21.43                1.5   
45          0            0                          100.00                3.7   
46          0            0                            0.00                0.3   
47          2            0                           55.56                1.9   
...       ...          ...                             ...                ...   
27719       0            1                           28.57                1.4   
27720       2            1                           59.09                1.9   
27721       2            1                           40.91                1.0   
27722       2            1                           70.00                2.8   
27723       2            1                           59.09                1.9   

       home_team_but_enc  away_team_pourcentage_victoire  away_team_but_mis  \
43                   2.2                            0.00                3.0   
44                   2.9                             NaN                NaN   
45                   2.0                           41.67                2.4   
46                   4.0                           57.14                3.1   
47                   0.7                           21.43                1.5   
...                  ...                             ...                ...   
27719                1.5                           40.91                1.0   
27720                1.0                           70.00                2.8   
27721                1.2                           60.00                1.5   
27722                1.0                           60.00                1.5   
27723                1.0                           40.91                1.0   

       away_team_but_enc  Rang_home_team  Rang_away_team  Host  
43                   4.0             NaN             NaN     0  
44                   NaN             NaN             NaN     0  
45                   2.1             NaN             NaN     0  
46                   2.0             NaN             NaN     0  
47                   2.9             NaN             NaN     0  
...                  ...             ...             ...   ...  
27719                1.2            70.0            20.0     1  
27720                1.0             7.0             3.0     0  
27721                0.7            20.0            12.0     0  
27722                0.7             3.0            12.0     0  
27723                1.2             7.0            20.0     0  

[900 rows x 17 columns]

In [14]:
versus=versus.reset_index(inplace=False)

In [15]:
versus

index  date  home_team  home_score  away_score      away_team  \
0       43  1930    Belgium           0           3  United States   
1       44  1930     France           4           1         Mexico   
2       45  1930     Brazil           1           2     Yugoslavia   
3       46  1930       Peru           1           3        Romania   
4       47  1930  Argentina           1           0         France   
..     ...   ...        ...         ...         ...            ...   
895  27719  2018     Russia           3           4        Croatia   
896  27720  2018     France           1           0        Belgium   
897  27721  2018    Croatia           2           1        England   
898  27722  2018    Belgium           2           0        England   
899  27723  2018     France           4           2        Croatia   

     tournament  winner  phase_final  home_team_pourcentage_victoire  \
0             1       0            0                           38.46   
1             1       2            0                           21.43   
2             1       0            0                          100.00   
3             1       0            0                            0.00   
4             1       2            0                           55.56   
..          ...     ...          ...                             ...   
895           1       0            1                           28.57   
896           1       2            1                           59.09   
897           1       2            1                           40.91   
898           1       2            1                           70.00   
899           1       2            1                           59.09   

     home_team_but_mis  home_team_but_enc  away_team_pourcentage_victoire  \
0                  2.2                2.2                            0.00   
1                  1.5                2.9                             NaN   
2                  3.7                2.0                           41.67   
3                  0.3                4.0                           57.14   
4                  1.9                0.7                           21.43   
..                 ...                ...                             ...   
895                1.4                1.5                           40.91   
896                1.9                1.0                           70.00   
897                1.0                1.2                           60.00   
898                2.8                1.0                           60.00   
899                1.9                1.0                           40.91   

     away_team_but_mis  away_team_but_enc  Rang_home_team  Rang_away_team  \
0                  3.0                4.0             NaN             NaN   
1                  NaN                NaN             NaN             NaN   
2                  2.4                2.1             NaN             NaN   
3                  3.1                2.0             NaN             NaN   
4                  1.5                2.9             NaN             NaN   
..                 ...                ...             ...             ...   
895                1.0                1.2            70.0            20.0   
896                2.8                1.0             7.0             3.0   
897                1.5                0.7            20.0            12.0   
898                1.5                0.7             3.0            12.0   
899                1.0                1.2             7.0            20.0   

     Host  
0       0  
1       0  
2       0  
3       0  
4       0  
..    ...  
895     1  
896     0  
897     0  
898     0  
899     0  

[900 rows x 18 columns]

In [16]:
victoire_home = 0
victoire_away = 0
nul = 0
for i in range (len(versus)) :
    if versus.loc[i]["home_score"] == versus.loc[i]["away_score"]:
        nul +=1
    elif versus.loc[i]["home_score"] > versus.loc[i]["away_score"] :
        victoire_home +=1
    elif versus.loc[i]["home_score"] < versus.loc[i]["away_score"] :
        victoire_away +=1
    
poucentagevict_home = (victoire_home/ len(versus))*100
pourcentagevict_away = (victoire_away/ len(versus))*100
pourcentage_nul = (nul/len(versus))*100

In [17]:
print('Pourcentage de victoire a domicile :',poucentagevict_home)

Pourcentage de victoire a domicile : 47.333333333333336


In [18]:
print("Pourcentage de victoire a l'extérieur :",pourcentagevict_away)

Pourcentage de victoire a l'extérieur : 33.0


In [19]:
print('Pourcentage de match nul',pourcentage_nul)

Pourcentage de match nul 19.666666666666664


# 2.Traitement de la data

In [20]:
versus=versus.drop('home_score',axis=1)

In [21]:
versus=versus.drop('away_score',axis=1)

In [22]:
versus=versus.drop('home_team',axis=1)

In [23]:
versus=versus.drop('away_team',axis=1)

In [24]:
versus

index  date  tournament  winner  phase_final  \
0       43  1930           1       0            0   
1       44  1930           1       2            0   
2       45  1930           1       0            0   
3       46  1930           1       0            0   
4       47  1930           1       2            0   
..     ...   ...         ...     ...          ...   
895  27719  2018           1       0            1   
896  27720  2018           1       2            1   
897  27721  2018           1       2            1   
898  27722  2018           1       2            1   
899  27723  2018           1       2            1   

     home_team_pourcentage_victoire  home_team_but_mis  home_team_but_enc  \
0                             38.46                2.2                2.2   
1                             21.43                1.5                2.9   
2                            100.00                3.7                2.0   
3                              0.00                0.3                4.0   
4                             55.56                1.9                0.7   
..                              ...                ...                ...   
895                           28.57                1.4                1.5   
896                           59.09                1.9                1.0   
897                           40.91                1.0                1.2   
898                           70.00                2.8                1.0   
899                           59.09                1.9                1.0   

     away_team_pourcentage_victoire  away_team_but_mis  away_team_but_enc  \
0                              0.00                3.0                4.0   
1                               NaN                NaN                NaN   
2                             41.67                2.4                2.1   
3                             57.14                3.1                2.0   
4                             21.43                1.5                2.9   
..                              ...                ...                ...   
895                           40.91                1.0                1.2   
896                           70.00                2.8                1.0   
897                           60.00                1.5                0.7   
898                           60.00                1.5                0.7   
899                           40.91                1.0                1.2   

     Rang_home_team  Rang_away_team  Host  
0               NaN             NaN     0  
1               NaN             NaN     0  
2               NaN             NaN     0  
3               NaN             NaN     0  
4               NaN             NaN     0  
..              ...             ...   ...  
895            70.0            20.0     1  
896             7.0             3.0     0  
897            20.0            12.0     0  
898             3.0            12.0     0  
899             7.0            20.0     0  

[900 rows x 14 columns]

In [25]:
versus.dropna(axis=0,inplace=True)

In [26]:
versus['Rang_home_team']=(1.)/(versus['Rang_home_team'])

In [27]:
versus['Rang_away_team']=(1.)/(versus['Rang_away_team'])

In [28]:
versus

index  date  tournament  winner  phase_final  \
464  13493  1994           1       2            0   
465  13494  1994           1       1            0   
466  13495  1994           1       0            0   
467  13496  1994           1       0            0   
468  13497  1994           1       1            0   
..     ...   ...         ...     ...          ...   
895  27719  2018           1       0            1   
896  27720  2018           1       2            1   
897  27721  2018           1       2            1   
898  27722  2018           1       2            1   
899  27723  2018           1       2            1   

     home_team_pourcentage_victoire  home_team_but_mis  home_team_but_enc  \
464                           71.43                2.2                0.9   
465                           73.68                2.2                0.7   
466                           53.33                1.5                0.5   
467                           70.59                1.9                0.6   
468                           29.09                1.3                1.2   
..                              ...                ...                ...   
895                           28.57                1.4                1.5   
896                           59.09                1.9                1.0   
897                           40.91                1.0                1.2   
898                           70.00                2.8                1.0   
899                           59.09                1.9                1.0   

     away_team_pourcentage_victoire  away_team_but_mis  away_team_but_enc  \
464                           27.03                1.2                1.2   
465                           45.71                1.7                0.8   
466                           52.17                1.7                1.1   
467                           66.67                1.8                0.8   
468                           65.00                1.7                0.6   
..                              ...                ...                ...   
895                           40.91                1.0                1.2   
896                           70.00                2.8                1.0   
897                           60.00                1.5                0.7   
898                           60.00                1.5                0.7   
899                           40.91                1.0                1.2   

     Rang_home_team  Rang_away_team  Host  
464        1.000000        0.023256     0  
465        0.200000        0.027027     0  
466        0.058824        0.142857     0  
467        0.250000        0.071429     0  
468        0.043478        0.083333     1  
..              ...             ...   ...  
895        0.014286        0.050000     1  
896        0.142857        0.333333     0  
897        0.050000        0.083333     0  
898        0.333333        0.083333     0  
899        0.142857        0.050000     0  

[426 rows x 14 columns]

# 3.Convertion du dataframe en tableau

In [29]:
#Met y sous forme d'un tableau
y=versus[['winner']].values


In [30]:
X=versus[['Rang_home_team','Rang_away_team','Host']].values
X.shape

(426, 3)

# 4.Séparation de la data d'entraînement de la data de test

In [31]:
#X_train,X_test,Y_train,Y_test=train_test_split(X_scaled,y_scaled,test_size=0.3,random_state=0)  #pour utiliser la version normalisé
#X_train,X_test,Y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

# 4.Cross validation

In [32]:
for train_index,test_index in KFold(3,shuffle=True, random_state=0).split(X):
    X_train,X_test=X[train_index],X[test_index]
    y_train,y_test=y[train_index],y[test_index]

# 5.Création d'un réseau de Neurone Artificiel

In [33]:
model = Sequential()

model.add(Dense(32, input_dim=3))
model.add(Activation('relu'))


model.add(Dense(3))
model.add(Activation('softmax'))
model.compile(loss='sparse_categorical_crossentropy',optimizer='Adam',metrics=['sparse_categorical_accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                128       
                                                                 
 activation (Activation)     (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 3)                 99        
                                                                 
 activation_1 (Activation)   (None, 3)                 0         
                                                                 
Total params: 227
Trainable params: 227
Non-trainable params: 0
_________________________________________________________________


# 6.entraînement du model

In [34]:
model.fit(X_train,y_train,epochs=100,batch_size=1,verbose=1)

Epoch 1/100
284/284 [==============================] - 1s 1ms/step - loss: 1.0491 - sparse_categorical_accuracy: 0.4718
Epoch 2/100
284/284 [==============================] - 0s 1ms/step - loss: 0.9902 - sparse_categorical_accuracy: 0.5070
Epoch 3/100
284/284 [==============================] - 0s 1ms/step - loss: 0.9748 - sparse_categorical_accuracy: 0.5035
Epoch 4/100
284/284 [==============================] - 0s 1ms/step - loss: 0.9672 - sparse_categorical_accuracy: 0.5282
Epoch 5/100
284/284 [==============================] - 0s 1ms/step - loss: 0.9632 - sparse_categorical_accuracy: 0.5458
Epoch 6/100
284/284 [==============================] - 0s 1ms/step - loss: 0.9621 - sparse_categorical_accuracy: 0.5528
Epoch 7/100
284/284 [==============================] - 0s 1ms/step - loss: 0.9589 - sparse_categorical_accuracy: 0.5387
Epoch 8/100
284/284 [==============================] - 0s 1ms/step - loss: 0.9584 - sparse_categorical_accuracy: 0.5458
Epoch 9/100
284/284 [===================

# Sauvegarde du Model

In [119]:
model.save("fifa2022.h5")

In [120]:
model=tf.keras.models.load_model('fifa2022.h5')

# 7.Evaluation du model sur la data de test

In [35]:
test_loss, test_accuracy= model.evaluate(X_test,y_test)

5/5 [==============================] - 0s 2ms/step - loss: 1.0755 - sparse_categorical_accuracy: 0.5282


# 8.Prédiction / Chargement de la data à prédire

In [36]:
match_precedent_coupe=pd.read_excel("pronoanciennecoupe.xlsx")

In [37]:
poule=match_precedent_coupe

In [38]:
poule=poule.drop('winner',axis=1)
poule_Pays=match_precedent_coupe


In [39]:
poule=poule.drop('home_team',axis=1)

In [40]:
poule=poule.drop('away_team',axis=1)

In [41]:
poule['Rang_home_team']=(1.)/(poule['Rang_home_team'])

In [42]:
poule['Rang_away_team']=(1.)/(poule['Rang_away_team'])

In [43]:
X_pred=poule[['Rang_home_team','Rang_away_team','Host']].values


# Affichage de la prédiction des matchs de poule

In [44]:
prediction=model.predict(X_pred)
i=0

for pred in prediction:
    print('Pour le match entre',poule_Pays['home_team'][i],'et',poule_Pays['away_team'][i])
    if (np.argmax(pred))==2 :

        print('Victoire pour',poule_Pays['home_team'][i],'\n')
        match_precedent_coupe['pred'][i]=2
        if match_precedent_coupe['winner'][i]==match_precedent_coupe['pred'][i] :
            match_precedent_coupe['trouve'][i]=1
        else :
            match_precedent_coupe['trouve'][i]=0
        
        if match_precedent_coupe['trouve'][i]==0. :
            match_precedent_coupe['prono'][i]=-1
        else :
            if match_precedent_coupe['pred'][i]==2. :
                match_precedent_coupe['prono'][i]=(match_precedent_coupe['PronovicPays1'][i])-1
            elif match_precedent_coupe['pred'][i]==1. :
                match_precedent_coupe['prono'][i]=(match_precedent_coupe['Pronovicnul'][i])-1
            elif match_precedent_coupe['pred'][i]==0. :
                match_precedent_coupe['prono'][i]=(match_precedent_coupe['PronovicPays2'][i])-1
                
                
                


    elif (np.argmax(pred))==0:
        print('Victoire pour',poule_Pays['away_team'][i],'\n')
        match_precedent_coupe['pred'][i]=0
        if match_precedent_coupe['winner'][i]==match_precedent_coupe['pred'][i] :
            match_precedent_coupe['trouve'][i]=1
        else :
            match_precedent_coupe['trouve'][i]=0
        if match_precedent_coupe['trouve'][i]==0. :
            match_precedent_coupe['prono'][i]=-1
        else :
            if match_precedent_coupe['pred'][i]==2. :
                match_precedent_coupe['prono'][i]=(match_precedent_coupe['PronovicPays1'][i])-1
            elif match_precedent_coupe['pred'][i]==1. :
                match_precedent_coupe['prono'][i]=(match_precedent_coupe['Pronovicnul'][i])-1
            elif match_precedent_coupe['pred'][i]==0. :
                match_precedent_coupe['prono'][i]=(match_precedent_coupe['PronovicPays2'][i])-1

    else :
        print('Match null\n')
        match_precedent_coupe['pred'][i]=1
        if match_precedent_coupe['winner'][i]==match_precedent_coupe['pred'][i] :
            match_precedent_coupe['trouve'][i]=1
        else :
            match_precedent_coupe['trouve'][i]=0
        if match_precedent_coupe['trouve'][i]==0. :
            match_precedent_coupe['prono'][i]=-1
        else :
            if match_precedent_coupe['pred'][i]==2. :
                match_precedent_coupe['prono'][i]=(match_precedent_coupe['PronovicPays1'][i])-1
            elif match_precedent_coupe['pred'][i]==1. :
                match_precedent_coupe['prono'][i]=(match_precedent_coupe['Pronovicnul'][i])-1
            elif match_precedent_coupe['pred'][i]==0. :
                match_precedent_coupe['prono'][i]=(match_precedent_coupe['PronovicPays2'][i])-1


    i=i+1


6/6 [==============================] - 0s 1ms/step
Pour le match entre South Africa et Mexico
Victoire pour South Africa 



C:\Users\chris\AppData\Local\Temp\ipykernel_13380\1938671058.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_precedent_coupe['pred'][i]=2
C:\Users\chris\AppData\Local\Temp\ipykernel_13380\1938671058.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_precedent_coupe['trouve'][i]=0
C:\Users\chris\AppData\Local\Temp\ipykernel_13380\1938671058.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_precedent_coupe['pro

Pour le match entre Uruguay et France
Victoire pour France 

Pour le match entre Argentina et Nigeria
Victoire pour Argentina 

Pour le match entre England et United States
Victoire pour England 

Pour le match entre South Korea et Greece
Victoire pour Greece 

Pour le match entre Algeria et Slovenia
Victoire pour Algeria 

Pour le match entre Germany et Australia
Victoire pour Germany 

Pour le match entre Serbia et Ghana
Victoire pour Serbia 

Pour le match entre Italy et Paraguay
Victoire pour Italy 

Pour le match entre Japan et Cameroon
Victoire pour Cameroon 

Pour le match entre Netherlands et Denmark
Victoire pour Netherlands 

Pour le match entre Brazil et North Korea
Victoire pour Brazil 

Pour le match entre Ivory Coast et Portugal
Victoire pour Portugal 

Pour le match entre New Zealand et Slovakia
Victoire pour New Zealand 

Pour le match entre Honduras et Chile
Victoire pour Chile 

Pour le match entre South Africa et Uruguay
Victoire pour South Africa 



C:\Users\chris\AppData\Local\Temp\ipykernel_13380\1938671058.py:33: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_precedent_coupe['trouve'][i]=1
C:\Users\chris\AppData\Local\Temp\ipykernel_13380\1938671058.py:44: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_precedent_coupe['prono'][i]=(match_precedent_coupe['PronovicPays2'][i])-1


Pour le match entre Spain et Switzerland
Victoire pour Spain 

Pour le match entre Argentina et South Korea
Victoire pour Argentina 

Pour le match entre France et Mexico
Victoire pour France 

Pour le match entre Greece et Nigeria
Victoire pour Greece 

Pour le match entre England et Algeria
Victoire pour England 

Pour le match entre Germany et Serbia
Victoire pour Germany 

Pour le match entre Slovenia et United States
Victoire pour United States 

Pour le match entre Cameroon et Denmark
Victoire pour Cameroon 

Pour le match entre Ghana et Australia
Victoire pour Australia 

Pour le match entre Netherlands et Japan
Victoire pour Netherlands 

Pour le match entre Brazil et Ivory Coast
Victoire pour Brazil 

Pour le match entre Italy et New Zealand
Victoire pour Italy 

Pour le match entre Slovakia et Paraguay
Victoire pour Slovakia 

Pour le match entre Chile et Switzerland
Victoire pour Chile 

Pour le match entre Portugal et North Korea
Victoire pour Portugal 

Pour le match entre

Pour le match entre Poland et Senegal
Victoire pour Poland 

Pour le match entre Russia et Egypt
Victoire pour Russia 

Pour le match entre Portugal et Morocco
Victoire pour Portugal 

Pour le match entre Uruguay et Saudi Arabia
Victoire pour Uruguay 

Pour le match entre Iran et Spain
Victoire pour Spain 

Pour le match entre Denmark et Australia
Victoire pour Denmark 

Pour le match entre France et Peru
Victoire pour France 

Pour le match entre Argentina et Croatia
Victoire pour Argentina 

Pour le match entre Brazil et Costa Rica
Victoire pour Brazil 

Pour le match entre Nigeria et Iceland
Victoire pour Iceland 

Pour le match entre Serbia et Switzerland
Victoire pour Switzerland 

Pour le match entre Belgium et Tunisia
Victoire pour Belgium 

Pour le match entre South Korea et Mexico
Victoire pour Mexico 

Pour le match entre Germany et Sweden
Victoire pour Germany 

Pour le match entre England et Panama
Victoire pour England 

Pour le match entre Japan et Senegal
Victoire pour S

In [54]:
for i in range (30,60):
    print(prediction[i],i)

[0.07183301 0.11476108 0.81340593] 30
[0.10763895 0.07000475 0.8223563 ] 31
[0.534799   0.16519381 0.30000716] 32
[0.36730406 0.23043115 0.4022648 ] 33
[0.2827012  0.26004356 0.45725518] 34
[0.14322533 0.23491138 0.62186325] 35
[0.39610228 0.22711918 0.3767785 ] 36
[0.6240521  0.14377464 0.23217316] 37
[0.5755105  0.16991884 0.25457066] 38
[0.27126852 0.24656145 0.48217008] 39
[0.64993733 0.10773883 0.24232385] 40
[0.31776747 0.2641819  0.41805062] 41
[0.28766742 0.26752487 0.4448077 ] 42
[0.6505793  0.12627074 0.22315003] 43
[0.7152011  0.03583433 0.24896455] 44
[0.3900134  0.25489342 0.35509312] 45
[0.6099853  0.00219259 0.38782206] 46
[0.30445763 0.25921726 0.43632513] 47
[0.25882143 0.2547475  0.48643106] 48
[0.2665916  0.2473935  0.48601493] 49
[0.21406765 0.20869543 0.57723695] 50
[0.31693122 0.17374508 0.5093238 ] 51
[0.24566433 0.01331583 0.7410198 ] 52
[0.08559486 0.15129678 0.7631083 ] 53
[0.310236   0.26346606 0.4262979 ] 54
[0.5546021  0.03809018 0.4073077 ] 55
[0.5727314  

In [55]:
match_precedent_coupe[30:60]

date      home_team  home_score  away_score    away_team  tournament  \
30  2010       Portugal           7           0  North Korea           1   
31  2010          Spain           2           0     Honduras           1   
32  2010         Greece           0           2    Argentina           1   
33  2010         Mexico           0           1      Uruguay           1   
34  2010        Nigeria           2           2  South Korea           1   
35  2010   South Africa           2           1       France           1   
36  2010      Australia           2           1       Serbia           1   
37  2010          Ghana           0           1      Germany           1   
38  2010       Slovenia           0           1      England           1   
39  2010  United States           1           0      Algeria           1   
40  2010       Cameroon           1           2  Netherlands           1   
41  2010        Denmark           1           3        Japan           1   
42  2010       Paraguay           0           0  New Zealand           1   
43  2010       Slovakia           3           2        Italy           1   
44  2010          Chile           1           2        Spain           1   
45  2010    North Korea           0           3  Ivory Coast           1   
46  2010       Portugal           0           0       Brazil           1   
47  2010    Switzerland           0           0     Honduras           1   
48  2010        Uruguay           2           1  South Korea           1   
49  2010  United States           1           2        Ghana           1   
50  2010      Argentina           3           1       Mexico           1   
51  2010        Germany           4           1      England           1   
52  2010         Brazil           3           0        Chile           1   
53  2010    Netherlands           2           1     Slovakia           1   
54  2010       Paraguay           5           3        Japan           1   
55  2010          Spain           1           0     Portugal           1   
56  2010    Netherlands           2           1       Brazil           1   
57  2010        Uruguay           4           2        Ghana           1   
58  2010      Argentina           0           4      Germany           1   
59  2010       Paraguay           0           1        Spain           1   

    winner  phase_final  home_team_pourcentage_victoire  home_team_but_mis  \
30       2            0                           71.43                2.0   
31       2            0                           84.62                2.7   
32       0            0                           42.11                1.2   
33       0            0                           56.76                1.9   
34       1            0                           45.00                1.3   
35       2            0                           40.00                1.0   
36       2            0                           50.00                1.0   
37       0            0                           39.13                1.2   
38       0            0                           55.56                1.8   
39       2            0                           50.00                1.7   
40       0            0                           45.45                1.6   
41       0            0                           40.00                1.2   
42       1            0                           37.50                1.1   
43       2            0                           38.10                1.5   
44       0            0                           65.38                1.7   
45       0            0                           33.33                1.3   
46       1            0                           71.43                2.0   
47       1            0                           33.33                1.2   
48       2            1                           55.56                1.9   
49       0            1                           50.00                1.7   
50       

# Génération du fihier avec les pronos

In [56]:
match_precedent_coupe.to_csv('sortieprono.csv',header=True,index=False)

# Traitement des pronostiques

In [57]:
#Résultat prono coupe du monde 2010

In [58]:
prono2010=match_precedent_coupe[match_precedent_coupe['date']==2010]

In [59]:
phase_final2010=prono2010[prono2010['phase_final']==1]

In [60]:
phase_final2010.head(32)

date      home_team  home_score  away_score    away_team  tournament  \
48  2010        Uruguay           2           1  South Korea           1   
49  2010  United States           1           2        Ghana           1   
50  2010      Argentina           3           1       Mexico           1   
51  2010        Germany           4           1      England           1   
52  2010         Brazil           3           0        Chile           1   
53  2010    Netherlands           2           1     Slovakia           1   
54  2010       Paraguay           5           3        Japan           1   
55  2010          Spain           1           0     Portugal           1   
56  2010    Netherlands           2           1       Brazil           1   
57  2010        Uruguay           4           2        Ghana           1   
58  2010      Argentina           0           4      Germany           1   
59  2010       Paraguay           0           1        Spain           1   
60  2010        Uruguay           2           3  Netherlands           1   
61  2010        Germany           0           1        Spain           1   
62  2010        Uruguay           2           3      Germany           1   
63  2010    Netherlands           0           1        Spain           1   

    winner  phase_final  home_team_pourcentage_victoire  home_team_but_mis  \
48       2            1                           55.56                1.9   
49       0            1                           50.00                1.7   
50       2            1                           69.57                1.9   
51       2            1                           66.67                2.4   
52       2            1                           83.33                2.3   
53       2            1                           71.43                2.2   
54       2            1                           37.50                1.1   
55       2            1                           84.62                2.7   
56       2            1                           71.43                2.2   
57       2            1                           55.56                1.9   
58       0            1                           69.57                1.9   
59       0            1                           37.50                1.1   
60       0            1                           55.56                1.9   
61       0            1                           66.67                2.4   
62       0            1                           55.56                1.9   
63       0            1                           71.43                2.2   

    ...  away_team_but_enc  Rang_home_team  Rang_away_team  Host  \
48  ...                0.7              16              47     0   
49  ...                1.0              14              32     0   
50  ...                0.8               7              17     0   
51  ...                0.8               6               8     0   
52  ...                0.9               1              18     0   
53  ...                1.3               4              34     0   
54  ...                0.9              31              45     0   
55  ...                0.5               2               3     0   
56  ...                0.6               4               1     0   
57  ...                1.0              16              32     0   
58  ...                0.6               7               6     0   
59  ...                1.0              31               2     0   
60  ...                0.5              16               4     0   
61  ...                1.0               6               2     0   
62  ...                0.6              16               6     0   
63  ...                1.0               4               2     0   

    PronovicPays1  Pronovicnul  PronovicPays2  pred trouve  prono  
48           1.70            3           4.40   2.0    1.0   0.70  
49           2.20          2.9           2.85   2.0    0.0  -1.00  
50           2.65      

# performance 2010

In [61]:
total2010=prono2010['prono'].sum()

In [62]:
totalphase_final2010=phase_final2010['prono'].sum()
print(totalphase_final2010)

8.81


In [63]:
print(totalphase_final2010)

8.81


In [64]:
total2010

-8.469999999999999

In [65]:
test=prono2010[prono2010['winner']==1]

In [66]:
test['winner'].sum()

14

In [67]:
bonpari2010=((prono2010['trouve'].sum())/len(prono2010))*100
print('Le pourcentage de paris trouvés sur la coupe du monde 2010 est de : ',bonpari2010,' %')

Le pourcentage de paris trouvés sur la coupe du monde 2010 est de :  51.5625  %


# prono2014

In [68]:
prono2014=match_precedent_coupe[match_precedent_coupe['date']==2014]

In [69]:
phase_final2014=prono2014[prono2014['phase_final']==1]

In [70]:
totalphase_final2014=phase_final2014['prono'].sum()
print(totalphase_final2014)

6.2299999999999995


In [71]:
total2014=prono2014['prono'].sum()

In [72]:
print(total2014)

17.560000000000002


In [73]:
bonpari2014=((prono2014['trouve'].sum())/len(prono2014))*100
print('Le pourcentage de paris trouvés sur la coupe du monde 2014 est de : ',bonpari2014,' %')

Le pourcentage de paris trouvés sur la coupe du monde 2014 est de :  65.625  %


# prono2018

In [74]:
prono2018=match_precedent_coupe[match_precedent_coupe['date']==2018]

In [75]:
total2018=prono2018['prono'].sum()

In [76]:
phase_final2018=prono2018[prono2018['phase_final']==1]

In [77]:
totalphase_final2018=phase_final2018['prono'].sum()
print(totalphase_final2018)

3.7700000000000005


In [78]:
print(total2018)

20.57


In [79]:
bonpari2018=((prono2018['trouve'].sum())/len(prono2018))*100
print('Le pourcentage de paris trouvés sur la coupe du monde 2018 est de : ',bonpari2018,' %')

Le pourcentage de paris trouvés sur la coupe du monde 2018 est de :  56.25  %


In [80]:
prono2018.head(10)

date   home_team  home_score  away_score     away_team  tournament  \
128  2018      Russia           5           0  Saudi Arabia           1   
129  2018       Egypt           0           1       Uruguay           1   
130  2018     Morocco           0           1          Iran           1   
131  2018    Portugal           3           3         Spain           1   
132  2018      France           2           1     Australia           1   
133  2018   Argentina           1           1       Iceland           1   
134  2018        Peru           0           1       Denmark           1   
135  2018     Croatia           2           0       Nigeria           1   
136  2018  Costa Rica           0           1        Serbia           1   
137  2018     Germany           0           1        Mexico           1   

     winner  phase_final  home_team_pourcentage_victoire  home_team_but_mis  \
128       2            0                           28.57                1.4   
129       0            0                           52.00                1.4   
130       0            0                           68.97                1.9   
131       1            0                           61.54                2.0   
132       2            0                           59.09                1.9   
133       1            0                           57.89                1.7   
134       0            0                           50.00                1.5   
135       2            0                           40.91                1.0   
136       0            0                           35.71                1.1   
137       0            0                           56.00                2.2   

     ...  away_team_but_enc  Rang_home_team  Rang_away_team  Host  \
128  ...                1.5              70              67     1   
129  ...                1.4              45              14     0   
130  ...                0.6              41              37     0   
131  ...                0.9               4              10     0   
132  ...                1.1               7              36     0   
133  ...                1.5               5              22     0   
134  ...                0.5              11              12     0   
135  ...                1.0              20              48     0   
136  ...                0.7              23              34     0   
137  ...                1.1               1              15     0   

     PronovicPays1  Pronovicnul  PronovicPays2  pred trouve  prono  
128           1.42         4.25           9.50   2.0    1.0   0.42  
129           8.50          4.1           1.45   0.0    1.0   0.45  
130           2.20         2.85           4.20   2.0    0.0  -1.00  
131           4.40          3.3           1.95   2.0    0.0  -1.00  
132           1.25          7.5          11.00   2.0    1.0   0.25  
133           1.29          5.4          12.00   2.0    0.0  -1.00  
134           3.40          3.1           2.30   2.0    0.0  -1.00  
135           1.62         3.75           6.00   2.0    1.0   0.62  
136           5.40          3.3           1.80   2.0    0.0  -1.00  
137           1.40          4.8           8.50   2.0    0.0  -1.00  

[10 rows x 23 columns]

In [81]:
phase_final2010

date      home_team  home_score  away_score    away_team  tournament  \
48  2010        Uruguay           2           1  South Korea           1   
49  2010  United States           1           2        Ghana           1   
50  2010      Argentina           3           1       Mexico           1   
51  2010        Germany           4           1      England           1   
52  2010         Brazil           3           0        Chile           1   
53  2010    Netherlands           2           1     Slovakia           1   
54  2010       Paraguay           5           3        Japan           1   
55  2010          Spain           1           0     Portugal           1   
56  2010    Netherlands           2           1       Brazil           1   
57  2010        Uruguay           4           2        Ghana           1   
58  2010      Argentina           0           4      Germany           1   
59  2010       Paraguay           0           1        Spain           1   
60  2010        Uruguay           2           3  Netherlands           1   
61  2010        Germany           0           1        Spain           1   
62  2010        Uruguay           2           3      Germany           1   
63  2010    Netherlands           0           1        Spain           1   

    winner  phase_final  home_team_pourcentage_victoire  home_team_but_mis  \
48       2            1                           55.56                1.9   
49       0            1                           50.00                1.7   
50       2            1                           69.57                1.9   
51       2            1                           66.67                2.4   
52       2            1                           83.33                2.3   
53       2            1                           71.43                2.2   
54       2            1                           37.50                1.1   
55       2            1                           84.62                2.7   
56       2            1                           71.43                2.2   
57       2            1                           55.56                1.9   
58       0            1                           69.57                1.9   
59       0            1                           37.50                1.1   
60       0            1                           55.56                1.9   
61       0            1                           66.67                2.4   
62       0            1                           55.56                1.9   
63       0            1                           71.43                2.2   

    ...  away_team_but_enc  Rang_home_team  Rang_away_team  Host  \
48  ...                0.7              16              47     0   
49  ...                1.0              14              32     0   
50  ...                0.8               7              17     0   
51  ...                0.8               6               8     0   
52  ...                0.9               1              18     0   
53  ...                1.3               4              34     0   
54  ...                0.9              31              45     0   
55  ...                0.5               2               3     0   
56  ...                0.6               4               1     0   
57  ...                1.0              16              32     0   
58  ...                0.6               7               6     0   
59  ...                1.0              31               2     0   
60  ...                0.5              16               4     0   
61  ...                1.0               6               2     0   
62  ...                0.6              16               6     0   
63  ...                1.0               4               2     0   

    PronovicPays1  Pronovicnul  PronovicPays2  pred trouve  prono  
48           1.70            3           4.40   2.0    1.0   0.70  
49           2.20          2.9           2.85   2.0    0.0  -1.00  
50           2.65      

In [82]:
phase_final2014

date    home_team  home_score  away_score      away_team  tournament  \
112  2014       Brazil           3           2          Chile           1   
113  2014     Colombia           2           0        Uruguay           1   
114  2014   Costa Rica           5           3         Greece           1   
115  2014  Netherlands           2           1         Mexico           1   
116  2014       France           2           0        Nigeria           1   
117  2014      Germany           2           1        Algeria           1   
118  2014    Argentina           1           0    Switzerland           1   
119  2014      Belgium           2           1  United States           1   
120  2014       Brazil           2           1       Colombia           1   
121  2014       France           0           1        Germany           1   
122  2014    Argentina           1           0        Belgium           1   
123  2014  Netherlands           4           3     Costa Rica           1   
124  2014       Brazil           1           7        Germany           1   
125  2014  Netherlands           2           4      Argentina           1   
126  2014       Brazil           0           3    Netherlands           1   
127  2014      Germany           1           0      Argentina           1   

     winner  phase_final  home_team_pourcentage_victoire  home_team_but_mis  \
112       2            1                           76.92                2.7   
113       2            1                           56.25                1.6   
114       2            1                           51.61                1.5   
115       2            1                           50.00                2.1   
116       2            1                           54.55                2.0   
117       2            1                           63.64                2.5   
118       2            1                           60.00                2.2   
119       2            1                           65.00                2.0   
120       2            1                           76.92                2.7   
121       0            1                           54.55                2.0   
122       2            1                           60.00                2.2   
123       2            1                           50.00                2.1   
124       0            1                           76.92                2.7   
125       0            1                           50.00                2.1   
126       0            1                           76.92                2.7   
127       2            1                           63.64                2.5   

     ...  away_team_but_enc  Rang_home_team  Rang_away_team  Host  \
112  ...                0.9               3              14     1   
113  ...                1.0               8               7     0   
114  ...                0.8              28              12     0   
115  ...                1.0              15              20     0   
116  ...                1.1              17              44     0   
117  ...                0.8               2              22     0   
118  ...                0.8               5               6     0   
119  ...                1.1              11              13     0   
120  ...                0.7               3               8     1   
121  ...                1.2              17               2     0   
122  ...                0.8               5              11     0   
123  ...                0.9              15              28     0   
124  ...                1.2               3               2     1   
125  ...                0.8              15               5     0   
126  ...                0.9               3              15     1   
127  ...                0.8               2               5     0   

     PronovicPays1  Pronovicnul  PronovicPays2  pred trouve  prono  
112           1.50         4.25           5.50   2.0    1.0   0.50  
113           2.05          3.3        

In [83]:
phase_final2018

date home_team  home_score  away_score    away_team  tournament  winner  \
177  2018   Uruguay           2           1     Portugal           1       2   
178  2018    Russia           4           3        Spain           1       2   
179  2018   Croatia           3           2      Denmark           1       2   
180  2018    Brazil           2           0       Mexico           1       2   
181  2018   Belgium           3           2        Japan           1       2   
182  2018    Sweden           1           0  Switzerland           1       2   
183  2018  Colombia           3           4      England           1       0   
184  2018   Uruguay           0           2       France           1       0   
185  2018    Brazil           1           2      Belgium           1       0   
186  2018    Sweden           0           2      England           1       0   
187  2018    Russia           3           4      Croatia           1       0   
188  2018    France           1           0      Belgium           1       2   
189  2018   Croatia           2           1      England           1       2   
190  2018   Belgium           2           0      England           1       2   
191  2018    France           4           2      Croatia           1       2   

     phase_final  home_team_pourcentage_victoire  home_team_but_mis  ...  \
177            1                           33.33                1.3  ...   
178            1                           28.57                1.4  ...   
179            1                           40.91                1.0  ...   
180            1                           80.95                2.0  ...   
181            1                           70.00                2.8  ...   
182            1                           39.13                1.5  ...   
183            1                           44.44                1.6  ...   
184            1                           33.33                1.3  ...   
185            1                           80.95                2.0  ...   
186            1                           39.13                1.5  ...   
187            1                           28.57                1.4  ...   
188            1                           59.09                1.9  ...   
189            1                           40.91                1.0  ...   
190            1                           70.00                2.8  ...   
191            1                           59.09                1.9  ...   

     away_team_but_enc  Rang_home_team  Rang_away_team  Host  PronovicPays1  \
177                0.7              14               4     0           2.80   
178                0.9              70              10     1           1.60   
179                0.5              20              12     0           1.85   
180                1.1               2              15     0           1.52   
181                1.3               3              61     0           1.42   
182                0.6              24               6     0           3.10   
183                0.7              16              12     0           3.90   
184                1.0              14               7     0           4.60   
185                1.0               2               3     0           2.10   
186                0.7              24              12     0           5.35   
187                1.2              70              20     1           4.50   
188                1.0               7               3     0           2.60   
189                0.7              20              12     0           3.75   
190                0.7               3              12     0           2.20   
191                1.2               7              20     0           2.00   

     Pronovicnul  PronovicPays2  pred trouve  prono  
177            3           3.00   0.0    0.0  -1.00  
178          3.9           6.75   2.0    1.0   0.60  
179          3.3           5.00   0.0    0.0  -1.00  
180          4.2          

# Coupe du Monde 2022

# Chargement du model

In [ ]:
model=tf.keras.models.load_model('fifa2022.h5')

In [ ]:
#Chargement des matchs de la coupe du monde

In [84]:
match_coupe2022=pd.read_excel("prono2022.xlsx")

In [ ]:
#Nettoyage

In [85]:
poule=match_coupe2022

In [86]:
poule=poule.drop('winner',axis=1)
poule_Pays=match_coupe2022


In [87]:
poule=poule.drop('home_team',axis=1)

In [88]:
poule=poule.drop('away_team',axis=1)

In [89]:
poule['Rang_home_team']=(1.)/(poule['Rang_home_team'])

In [90]:
poule['Rang_away_team']=(1.)/(poule['Rang_away_team'])

In [91]:
X_pred=poule[['Rang_home_team','Rang_away_team','Host']].values

# Prédiction des matchs 2022

In [92]:
prediction=model.predict(X_pred)
i=0

for pred in prediction:
    print('Pour le match entre',poule_Pays['home_team'][i],'et',poule_Pays['away_team'][i])
    if (np.argmax(pred))==2 :

        print('Victoire pour',poule_Pays['home_team'][i],'\n')
        match_coupe2022['pred'][i]=2
        if match_coupe2022['winner'][i]==match_coupe2022['pred'][i] :
            match_coupe2022['trouve'][i]=1
        else :
            match_coupe2022['trouve'][i]=0
        
        if match_coupe2022['trouve'][i]==0. :
            match_coupe2022['prono'][i]=-1
        else :
            if match_coupe2022['pred'][i]==2. :
                match_coupe2022['prono'][i]=(match_coupe2022['PronovicPays1'][i])-1
            elif match_coupe2022['pred'][i]==1. :
                match_coupe2022['prono'][i]=(match_coupe2022['Pronovicnul'][i])-1
            elif match_coupe2022['pred'][i]==0. :
                match_coupe2022['prono'][i]=(match_coupe2022['PronovicPays2'][i])-1
                
                
                


    elif (np.argmax(pred))==0:
        print('Victoire pour',poule_Pays['away_team'][i],'\n')
        match_coupe2022['pred'][i]=0
        if match_coupe2022['winner'][i]==match_coupe2022['pred'][i] :
            match_coupe2022['trouve'][i]=1
        else :
            match_coupe2022['trouve'][i]=0
        if match_coupe2022['trouve'][i]==0. :
            match_coupe2022['prono'][i]=-1
        else :
            if match_coupe2022['pred'][i]==2. :
                match_coupe2022['prono'][i]=(match_coupe2022['PronovicPays1'][i])-1
            elif match_coupe2022['pred'][i]==1. :
                match_coupe2022['prono'][i]=(match_coupe2022['Pronovicnul'][i])-1
            elif match_coupe2022['pred'][i]==0. :
                match_coupe2022['prono'][i]=(match_coupe2022['PronovicPays2'][i])-1

    else :
        print('Match null\n')
        match_coupe2022['pred'][i]=1
        if match_coupe2022['winner'][i]==match_coupe2022['pred'][i] :
            match_coupe2022['trouve'][i]=1
        else :
            match_coupe2022['trouve'][i]=0
        if match_coupe2022['trouve'][i]==0. :
            match_coupe2022['prono'][i]=-1
        else :
            if match_coupe2022['pred'][i]==2. :
                match_coupe2022['prono'][i]=(match_coupe2022['PronovicPays1'][i])-1
            elif match_coupe2022['pred'][i]==1. :
                match_coupe2022['prono'][i]=(match_coupe2022['Pronovicnul'][i])-1
            elif match_coupe2022['pred'][i]==0. :
                match_coupe2022['prono'][i]=(match_coupe2022['PronovicPays2'][i])-1


    i=i+1

2/2 [==============================] - 0s 3ms/step
Pour le match entre Qatar et Ecuador
Victoire pour Qatar 

Pour le match entre England et Iran
Victoire pour England 

Pour le match entre Senegal et Netherlands
Victoire pour Netherlands 

Pour le match entre United States et Wales
Victoire pour United States 



C:\Users\chris\AppData\Local\Temp\ipykernel_13380\98871231.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_coupe2022['pred'][i]=2
C:\Users\chris\AppData\Local\Temp\ipykernel_13380\98871231.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_coupe2022['trouve'][i]=0
C:\Users\chris\AppData\Local\Temp\ipykernel_13380\98871231.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_coupe2022['prono'][i]=-1
C:\Users\chri

Pour le match entre Argentina et Saudi Arabia
Victoire pour Argentina 

Pour le match entre Denmark et Tunisia
Victoire pour Denmark 

Pour le match entre Mexico et Poland
Victoire pour Mexico 

Pour le match entre France et Australia
Victoire pour France 

Pour le match entre Morocco et Croatia
Victoire pour Croatia 

Pour le match entre Germany et Japan
Victoire pour Germany 

Pour le match entre Spain et Costa Rica
Victoire pour Spain 

Pour le match entre Belgium et Canada
Victoire pour Belgium 

Pour le match entre Switzerland et Cameroon

C:\Users\chris\AppData\Local\Temp\ipykernel_13380\98871231.py:35: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_coupe2022['trouve'][i]=0
C:\Users\chris\AppData\Local\Temp\ipykernel_13380\98871231.py:37: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  match_coupe2022['prono'][i]=-1



Victoire pour Switzerland 

Pour le match entre Uruguay et South Korea
Victoire pour Uruguay 

Pour le match entre Portugal et Ghana
Victoire pour Portugal 

Pour le match entre Brazil et Serbia
Victoire pour Brazil 

Pour le match entre Wales et Iran
Victoire pour Wales 

Pour le match entre Qatar et Senegal
Victoire pour Qatar 

Pour le match entre Netherlands et Ecuador
Victoire pour Netherlands 

Pour le match entre England et United States
Victoire pour England 

Pour le match entre Tunisia et Australia
Victoire pour Tunisia 

Pour le match entre Poland et Saudi Arabia
Victoire pour Poland 

Pour le match entre France et Denmark
Victoire pour France 

Pour le match entre Argentina et Mexico
Victoire pour Argentina 

Pour le match entre Japan et Costa Rica
Victoire pour Japan 

Pour le match entre Belgium et Morocco
Victoire pour Belgium 

Pour le match entre Croatia et Canada
Victoire pour Croatia 

Pour le match entre Spain et Germany
Victoire pour Spain 

Pour le match entre Ca

In [93]:
match_coupe2022

date      home_team  home_score  away_score     away_team  tournament  \
0   2022          Qatar           0           2       Ecuador           1   
1   2022        England           6           2          Iran           1   
2   2022        Senegal           0           2   Netherlands           1   
3   2022  United States           1           1         Wales           1   
4   2022      Argentina           1           2  Saudi Arabia           1   
..   ...            ...         ...         ...           ...         ...   
59  2022        England           1           2        France           1   
60  2022      Argentina           3           0       Croatia           1   
61  2022         France           2           0       Morocco           1   
62  2022        Croatia           2           1       Morocco           1   
63  2022      Argentina           4           3        France           1   

    winner  phase_final  home_team_pourcentage_victoire  home_team_but_mis  \
0        0            0                           50.00                1.4   
1        2            0                           68.00                2.3   
2        0            0                           62.96                1.6   
3        1            0                           68.75                2.0   
4        0            0                           68.18                1.9   
..     ...          ...                             ...                ...   
59       0            1                             NaN                NaN   
60       2            1                             NaN                NaN   
61       2            1                             NaN                NaN   
62       2            1                             NaN                NaN   
63       2            1                             NaN                NaN   

    ...  away_team_but_enc  Rang_home_team  Rang_away_team  Host  \
0   ...                1.0             150              44     1   
1   ...                0.4               5              20     0   
2   ...                1.0              18               8     0   
3   ...                1.2              16              19     0   
4   ...                0.6               3              51     0   
..  ...                ...             ...             ...   ...   
59  ...                NaN               5               4     0   
60  ...                NaN               3              12     0   
61  ...                NaN               4              22     0   
62  ...                NaN              12              22     0   
63  ...                NaN               3               4     0   

    PronovicPays1  Pronovicnul  PronovicPays2  pred  trouve  prono  
0            3.40         3.15           2.30   2.0     0.0  -1.00  
1            1.35         4.50          10.50   2.0     1.0   0.35  
2            6.25         3.65           1.60   0.0     1.0   0.60  
3            2.40         3.10           3.10   2.0     0.0  -1.00  
4            1.10        10.00          26.00   2.0     0.0  -1.00  
..            ...          ...            ...   ...     ...    ...  
59           2.90         3.15           2.75   2.0     0.0  -1.00  
60           2.00         3.10           4.35   2.0     1.0   1.00  
61           1.59         4.10           6.00   2.0     1.0   0.59  
62           2.20         3.65           3.15   2.0     1.0   1.20  
63           2.70         3.20           2.85   2.0     1.0   1.70  

[64 rows x 23 columns]

In [94]:
total2022=match_coupe2022['prono'].sum()

In [95]:
print (total2022)

2.759999999999998


In [96]:
trouve2022=match_coupe2022['trouve'].sum()

In [ ]:
#Affichage des resultats

# Résultat des paris pour 2022

In [108]:
print ("Pour la Coupe du monde 2022, nous avons trouvé "+ str(trouve2022)+" paris sur les : "+str(len(match_coupe2022)))

Pour la Coupe du monde 2022, nous avons trouvé 35.0 paris sur les : 64


In [109]:
print ("Soit "+str(trouve2022/(len(match_coupe2022))*100)+" %")

Soit 54.6875 %


In [111]:
print("Si 1€ parié à tous les matchs de la coupe le resultat final est : "+str(total2022))

Si 1€ parié à tous les matchs de la coupe le resultat final est : 2.759999999999998


# Optimisation

In [112]:
phase_final2022=match_coupe2022[match_coupe2022['phase_final']==1]

In [113]:
totalphase_final2022=phase_final2022['prono'].sum()
print(totalphase_final2022)

5.690000000000001


In [115]:
trouve_phase_final_2022=phase_final2022['trouve'].sum()
trouve_phase_final_2022

12.0

In [118]:
print ("Le pourcentage de matchs trouvés sur la phase finale est de : "+str(trouve_phase_final_2022/(len(phase_final2022))*100)+"%")

Le pourcentage de matchs trouvés sur la phase finale est de : 75.0%
